sudo: required
services:
    - docker

before_install:
    - docker build -t koagyu/react_travis -f Dockerfile.dev .

script:
    - docker run -e CI=true koagyu/react_travis npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "react_travis"
    env: "ReactTravis-env"
    bucket_name: "elasticbeanstalk-us-east-2-613636068067"
    bucket_path: "react_travis"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY